export const ROUTE = {
  SPLASH: 'Splash',
  LOGIN: 'Login',
  HOME: 'Home',
  PROFILE: 'Profile',
  DASHBOARD: 'Dashboard',
  EVENT: 'Event',
  PROFILE_SCREEN: 'ProfileScreen',
  UPDATE_PASSWORD: 'UpdatePassword',
  AUTH: 'Auth',
  TAB: 'Tab',
  PARENT_EDIT: 'Parent_Edit',
  PARENT_PRIVACY: 'Parent_Privacy',
  PARENT_PROFILE_EDIT: 'Parent_Profile_Edit',
};
